### PR TITLE
dragItems, panHandler, getDragItems and domElement

### PR DESCRIPTION
**Pull request by greglbd**
Added:
dragItems: allows you to specify which items in zpd are draggable
panHandler: true:false, sets the background layer as the only element that can pan the whole zpd object

getters:
domElement: quick access to the domElement - useful for easily adding and removing items from zpd
getDragItems: you can use this to get the current dragItems and add another item to the list then reinit.

I also did a mini refactor of the code to make it a bit more readable.

### CODE REVIEW

**Comment by cjgordon** [comment]
I have been testing this as I have the same requirement. I have found however it currently can't drag groups which is a requirement for the complex icons I need to drag. 

I found this solution in the mean time:
https://github.com/huei90/snap.svg.zpd/issues/24

**Comment by huei90** [comment]
@greglbd  seems the indent are all reconstruct, would you mind rebuild it with a new PR?

**Comment by greglbd** [comment]
@huei90 no problem, i'll try to do that this week.

**Comment by huei90** [comment]
@greglbd  Any update on this? Else I'm going to close it =)

**Comment by greglbd** [comment]
I will get round to this one. just doing the other one for you.

**Comment by huei90** [comment]
Ok then I close it.

**Pull request closed without merging**
