### PR TITLE
Zoom to element

### PR DESCRIPTION
**Pull request by justin-hackin**
Someone in the issues was requesting this and I had to implement it so I thought I'd integrate and make PR for it

### CODE REVIEW

**Comment by justin-hackin** [comment]
Please note this PR has changes for previous PR made for the enable/disable functionality.

**Comment by huei90** [comment]
Hi @justin-hackin Do you want to give me a PR again? Or else I will do it again.

**Comment by huei90** [comment]
Sorry that @justin-hackin I didn't follow up your PR. 

I have tried this but it doesn't work correctly.

**Comment by huei90** [comment]
nudge.

**Pull request closed without merging**
