### PR TITLE
Improve zoom to center

### PR DESCRIPTION
**Pull request by deerawan**
I moved some zoom to center codes from snap svg beta to here. Previous codes are not strong enough to handle zoom in more than one.

### CODE REVIEW

**Comment by huei90** [comment]
Cool, let's try it.

**Comment by huei90** [comment]
Hi @deerawan Thanks for this change! It's work as expected. But there is the situation not really true.

zoom after rotate the element, it will have a little bit lose on zoom. Try it.

**Comment by deerawan** [comment]
@huei90 ah yes, you are right. Hmm, let me try to find out the problem.

**Comment by huei90** [comment]
Thanks :+1:

**Pull request merged**
